# Generated by Django 5.1.9 on 2025-05-30 08:24

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neocad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformity',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=100)),
                ('site_id', models.CharField(max_length=100)),
                ('reported_by', models.EmailField(max_length=254)),
                ('issue_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photos', models.JSONField(blank=True, null=True)),
                ('severity', models.CharField(max_length=20)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('comments', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'neocad',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
