---
name: Checks

# trigger: This workflow is triggered on every push to the repository.
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # checkout the code from the repository
      - name: Checkout
        uses: actions/checkout@v2

      # # Test the code
      # - name: Test
      #   run: docker compose run --rm app sh -c "python manage.py test"

      # Lint the code
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"