---
name: Checks

# trigger: This workflow is triggered on every push to the repository.
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # checkout the code from the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .env file from secrets
        run: |
          echo "DEBUG=${{ secrets.DEBUG }}" >> .env
          echo "USERNAME_MONGODB=${{ secrets.USERNAME_MONGODB }}" >> .env
          echo "PASSWORD_MONGODB=${{ secrets.PASSWORD_MONGODB }}" >> .env
          echo "DATABASE_URL=mongodb+srv://${{ secrets.USERNAME_MONGODB }}:${{ secrets.PASSWORD_MONGODB }}@ac-ygvectq.gkbniau.mongodb.net/databaseproject?retryWrites=true&w=majority" >> .env
          # add more as needed

      # Test the code
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"

      # Lint the code
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"